name: Metrics

on:
  # Schedule daily updates
  schedule: 
    - cron: "0 0 * * *"
  # workflow mendeteksi waktu dan bekerja secara otomatis
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  # push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: starred repo
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.stars.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_stars: yes
          plugin_stars_limit: 4
       # - name: left profile
       #   uses: stalomeow/metrics@projects-v2
       #   with:
       #     token: ${{ secrets.METRICS_TOKEN }}
       #     filename: github-metrics-left.svg

       #     # Options
       #     user: trihajikhr
       #     template: classic
       #     base: header, activity, community
       #     config_timezone: Asia/Jakarta
       #     plugin_languages: yes
       #     plugin_languages_colors: github
       #     plugin_languages_limit: 8
       #     plugin_languages_sections: most-used
       #     # plugin_languages_ignored: html, css
       #     plugin_languages_details: percentage #, lines
       #     plugin_languages_indepth: no
       #     plugin_languages_analysis_timeout: 30
       #     # plugin_anilist: yes
       #     # plugin_anilist_user: Stalo
       #     # plugin_anilist_sections: characters
       #     # plugin_anilist_limit_characters: 22
       #     config_padding: 0, 8 + 11%
       #     config_order: base.header, base.activity+community, languages #, anilist

       # - name: right profile
       #   uses: stalomeow/metrics@projects-v2
       #   with:
       #     token: ${{ secrets.METRICS_TOKEN }}
       #     filename: github-metrics-achievement.svg

       #     # Options
       #     user: trihajikhr
       #     template: classic
       #     base: ""
       #     config_timezone: Asia/Jakarta
       #     plugin_achievements: yes
       #     plugin_achievements_threshold: X
       #     plugin_achievements_limit: 24
       #     plugin_achievements_display: compact
       #     # # plugin_stars: yes
       #     # # plugin_stars_limit: 2
       #     # config_padding: 0, 8 + 11%
       #     # config_order: achievements #, stars
          
       # - name: Full-year calendar
       #   uses: lowlighter/metrics@latest
       #   with:
       #     filename: metrics.plugin.isocalendar.fullyear.svg
       #     token: ${{ secrets.METRICS_TOKEN }}
       #     user: trihajikhr
       #     template: classic
       #     base: ""
       #     plugin_isocalendar: yes
       #     plugin_isocalendar_duration: full-year

       # - name: LeetCode
       #   uses: lowlighter/metrics@latest
       #   with:
       #     filename: metrics.plugin.leetcode.svg
       #     token: NOT_NEEDED
       #     base: ""
       #     plugin_leetcode: yes
       #     plugin_leetcode_user: RiverRis
       #     plugin_leetcode_sections: solved, skills, recent
