name: Metrics
on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: RiverRis
          template: classic
          base: header, activity, community, repositories
          config_timezone: Asia/Jakarta

          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_details: bytes-size, percentage

          plugin_leetcode: yes
          plugin_leetcode_user: RiverRis

          plugin_codeforces: yes
          plugin_codeforces_user: Riveris

          plugin_atcoder: yes
          plugin_atcoder_user: Riveris
