name: Metrics
on:
  schedule:
    - cron: "0 */6 * * *"   # setiap 6 jam
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: RiverRis
          template: classic
          base: header, activity, community, repositories
          config_timezone: Asia/Jakarta

          # LeetCode plugin
          plugin_leetcode: yes
          plugin_leetcode_user: RiverRis
